// Code generated by frontend/scripts/gen-tokens.mjs from design/tokens.json. DO NOT EDIT.

// Package design carries the design values the Go side reads. The frontend
// reads the same values from src/styles/tokens.ts, both from one source, so
// the window main.go opens is the window the layout was drawn for.
package design

// Window geometry, in logical pixels.
const (
	WindowWidth     = 1280
	WindowHeight    = 800
	WindowMinWidth  = 1024
	WindowMinHeight = 640
)

// WindowBackground is the page ground (color.surface.bg, dark), painted by the
// shell before the first frame so a slow WebView never flashes white.
var WindowBackground = [3]uint8{12, 12, 14}

// ChapterIDs is every chapter the token set names an accent for, in order.
// The launcher manifest may not name a chapter outside this list.
var ChapterIDs = []string{"luxemburg", "lichdenstein", "frangfurd"}
