// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckChapterMap(arg1) {
  return window['go']['main']['App']['CheckChapterMap'](arg1);
}

export function ChoosePrismExecutable() {
  return window['go']['main']['App']['ChoosePrismExecutable']();
}

export function ChoosePrismRoot() {
  return window['go']['main']['App']['ChoosePrismRoot']();
}

export function ClearPreviews() {
  return window['go']['main']['App']['ClearPreviews']();
}

export function CopyRedactedLog() {
  return window['go']['main']['App']['CopyRedactedLog']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetChangelogs() {
  return window['go']['main']['App']['GetChangelogs']();
}

export function GetChapterMods(arg1) {
  return window['go']['main']['App']['GetChapterMods'](arg1);
}

export function GetChapterSettings(arg1) {
  return window['go']['main']['App']['GetChapterSettings'](arg1);
}

export function GetEngine() {
  return window['go']['main']['App']['GetEngine']();
}

export function GetGameStates() {
  return window['go']['main']['App']['GetGameStates']();
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function GetManifest() {
  return window['go']['main']['App']['GetManifest']();
}

export function GetPackStates() {
  return window['go']['main']['App']['GetPackStates']();
}

export function GetPreviewSituations() {
  return window['go']['main']['App']['GetPreviewSituations']();
}

export function GetPrismRelease() {
  return window['go']['main']['App']['GetPrismRelease']();
}

export function GetRunLogs(arg1) {
  return window['go']['main']['App']['GetRunLogs'](arg1);
}

export function GetRunReport(arg1) {
  return window['go']['main']['App']['GetRunReport'](arg1);
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWikiArtStats() {
  return window['go']['main']['App']['GetWikiArtStats']();
}

export function GetWikiPages() {
  return window['go']['main']['App']['GetWikiPages']();
}

export function GetWikiShots() {
  return window['go']['main']['App']['GetWikiShots']();
}

export function InstallChapter(arg1) {
  return window['go']['main']['App']['InstallChapter'](arg1);
}

export function InstallPrism() {
  return window['go']['main']['App']['InstallPrism']();
}

export function LaunchChapter(arg1) {
  return window['go']['main']['App']['LaunchChapter'](arg1);
}

export function LeaveSplash() {
  return window['go']['main']['App']['LeaveSplash']();
}

export function LogFrontendError(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogFrontendError'](arg1, arg2, arg3);
}

export function OpenChapterWiki(arg1) {
  return window['go']['main']['App']['OpenChapterWiki'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenInstanceFolder(arg1) {
  return window['go']['main']['App']['OpenInstanceFolder'](arg1);
}

export function OpenWikiPage(arg1) {
  return window['go']['main']['App']['OpenWikiPage'](arg1);
}

export function ReadRunLog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadRunLog'](arg1, arg2, arg3, arg4);
}

export function RefreshEngine() {
  return window['go']['main']['App']['RefreshEngine']();
}

export function SaveChapterSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveChapterSettings'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetModsDisabled(arg1, arg2) {
  return window['go']['main']['App']['SetModsDisabled'](arg1, arg2);
}

export function SetPackSource(arg1, arg2) {
  return window['go']['main']['App']['SetPackSource'](arg1, arg2);
}

export function ShowInstanceInPrism(arg1) {
  return window['go']['main']['App']['ShowInstanceInPrism'](arg1);
}

export function ShowPrismConsole(arg1) {
  return window['go']['main']['App']['ShowPrismConsole'](arg1);
}

export function StartPreview(arg1, arg2) {
  return window['go']['main']['App']['StartPreview'](arg1, arg2);
}

export function StopGame(arg1) {
  return window['go']['main']['App']['StopGame'](arg1);
}

export function StopLiveLog(arg1) {
  return window['go']['main']['App']['StopLiveLog'](arg1);
}

export function WatchLiveLog(arg1) {
  return window['go']['main']['App']['WatchLiveLog'](arg1);
}
