// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAppVersion():Promise<string>;

export function GetEngine():Promise<models.EngineInfo>;

export function GetManifest():Promise<models.Manifest>;

export function GetServerStatus(arg1:string):Promise<models.ServerStatus>;

export function GetSettings():Promise<models.AppSettings>;

export function LaunchChapter(arg1:string):Promise<void>;

export function OpenChapterWiki(arg1:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function RefreshEngine():Promise<models.EngineInfo>;

export function SaveSettings(arg1:models.AppSettings):Promise<void>;
