// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ChoosePrismExecutable():Promise<string>;

export function ChoosePrismRoot():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetChapterSettings(arg1:string):Promise<models.ChapterSettingsInfo>;

export function GetEngine():Promise<models.EngineInfo>;

export function GetInstances():Promise<models.InstanceReport>;

export function GetManifest():Promise<models.Manifest>;

export function GetPrismRelease():Promise<models.PrismRelease>;

export function GetServerStatus(arg1:string):Promise<models.ServerStatus>;

export function GetSettings():Promise<models.AppSettings>;

export function GetWikiPages():Promise<Array<models.WikiPage>>;

export function InstallChapter(arg1:string):Promise<models.InstanceReport>;

export function InstallPrism():Promise<void>;

export function LaunchChapter(arg1:string):Promise<void>;

export function OpenChapterWiki(arg1:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenWikiPage(arg1:string):Promise<void>;

export function RefreshEngine():Promise<models.EngineInfo>;

export function SaveChapterSettings(arg1:string,arg2:models.ChapterSettings):Promise<models.ChapterSettingsInfo>;

export function SaveSettings(arg1:models.AppSettings):Promise<void>;
