// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetEngine() {
  return window['go']['main']['App']['GetEngine']();
}

export function GetManifest() {
  return window['go']['main']['App']['GetManifest']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function LaunchChapter(arg1) {
  return window['go']['main']['App']['LaunchChapter'](arg1);
}

export function OpenChapterWiki(arg1) {
  return window['go']['main']['App']['OpenChapterWiki'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function RefreshEngine() {
  return window['go']['main']['App']['RefreshEngine']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
