// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ChoosePrismExecutable():Promise<string>;

export function ChoosePrismRoot():Promise<string>;

export function ClearPreviews():Promise<void>;

export function CopyRedactedLog():Promise<number>;

export function GetAppVersion():Promise<string>;

export function GetChapterSettings(arg1:string):Promise<models.ChapterSettingsInfo>;

export function GetEngine():Promise<models.EngineInfo>;

export function GetGameStates():Promise<Array<models.GameState>>;

export function GetInstances():Promise<models.InstanceReport>;

export function GetManifest():Promise<models.Manifest>;

export function GetPackStates():Promise<Array<models.PackState>>;

export function GetPreviewSituations():Promise<Array<models.PreviewSituation>>;

export function GetPrismRelease():Promise<models.PrismRelease>;

export function GetRunLogs(arg1:string):Promise<Array<models.RunLog>>;

export function GetRunReport(arg1:string):Promise<models.RunReport>;

export function GetServerStatus(arg1:string):Promise<models.ServerStatus>;

export function GetSettings():Promise<models.AppSettings>;

export function GetWikiPages():Promise<Array<models.WikiPage>>;

export function GetWikiShots():Promise<Array<models.WikiShot>>;

export function InstallChapter(arg1:string):Promise<models.InstanceReport>;

export function InstallPrism():Promise<void>;

export function LaunchChapter(arg1:string):Promise<void>;

export function LeaveSplash():Promise<void>;

export function LogFrontendError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenChapterWiki(arg1:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenInstanceFolder(arg1:string):Promise<void>;

export function OpenWikiPage(arg1:string):Promise<void>;

export function ReadRunLog(arg1:string,arg2:string,arg3:string,arg4:number):Promise<models.RunLogText>;

export function RefreshEngine():Promise<models.EngineInfo>;

export function SaveChapterSettings(arg1:string,arg2:models.ChapterSettings):Promise<models.ChapterSettingsInfo>;

export function SaveSettings(arg1:models.AppSettings):Promise<void>;

export function SetPackSource(arg1:string,arg2:string):Promise<models.InstanceReport>;

export function ShowPrismConsole(arg1:string):Promise<boolean>;

export function StartPreview(arg1:string,arg2:string):Promise<models.PreviewStart>;

export function StopGame(arg1:string):Promise<models.GameState>;
