// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChoosePrismExecutable() {
  return window['go']['main']['App']['ChoosePrismExecutable']();
}

export function ChoosePrismRoot() {
  return window['go']['main']['App']['ChoosePrismRoot']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetChapterSettings(arg1) {
  return window['go']['main']['App']['GetChapterSettings'](arg1);
}

export function GetEngine() {
  return window['go']['main']['App']['GetEngine']();
}

export function GetGameStates() {
  return window['go']['main']['App']['GetGameStates']();
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function GetManifest() {
  return window['go']['main']['App']['GetManifest']();
}

export function GetPackStates() {
  return window['go']['main']['App']['GetPackStates']();
}

export function GetPrismRelease() {
  return window['go']['main']['App']['GetPrismRelease']();
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWikiPages() {
  return window['go']['main']['App']['GetWikiPages']();
}

export function InstallChapter(arg1) {
  return window['go']['main']['App']['InstallChapter'](arg1);
}

export function InstallPrism() {
  return window['go']['main']['App']['InstallPrism']();
}

export function LaunchChapter(arg1) {
  return window['go']['main']['App']['LaunchChapter'](arg1);
}

export function OpenChapterWiki(arg1) {
  return window['go']['main']['App']['OpenChapterWiki'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenInstanceFolder(arg1) {
  return window['go']['main']['App']['OpenInstanceFolder'](arg1);
}

export function OpenWikiPage(arg1) {
  return window['go']['main']['App']['OpenWikiPage'](arg1);
}

export function RefreshEngine() {
  return window['go']['main']['App']['RefreshEngine']();
}

export function SaveChapterSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveChapterSettings'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
